a = 200;
b = 1;
console.log(a * b);
console.log("ligadurai");
console.log("adhi");
console.log("lignadurai");
console.log("aathiiiiiiii");
console.log("checking");
console.log("aadhi branchhhh");
console.log("checking branches    ");
console.log("Radha");
